_wandb:
    value:
        cli_version: 0.27.0
        e:
            2vvaqteohyp5m5lwtun2a5loqid4xwrm:
                codePath: decoder_only_transformer\train\train.py
                codePathLocal: train.py
                cpu_count: 24
                cpu_count_logical: 32
                cudaVersion: "13.1"
                disk:
                    /:
                        total: "542217596928"
                        used: "503650947072"
                email: aarushgupta2735@gmail.com
                executable: C:\Users\admin\miniconda3\envs\rl-cuda-env\python.exe
                git:
                    commit: fcb0aba3459ec3649849e751549fb4aa1799d34f
                    remote: https://github.com/aarushgupta2735/SAIDL_Assignment
                gpu: NVIDIA GeForce RTX 5090
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Blackwell
                      cudaCores: 21760
                      memoryTotal: "34190917632"
                      name: NVIDIA GeForce RTX 5090
                      uuid: GPU-7ace31a7-d7b8-6589-efb6-20678510aec2
                host: DESKTOP-AO89QNU
                memory:
                    total: "68421812224"
                os: Windows-10-10.0.26200-SP0
                program: C:\Users\admin\Documents\SAIDL_Assignment\decoder_only_transformer\train\train.py
                python: CPython 3.11.15
                root: C:\Users\admin\Documents\SAIDL_Assignment\decoder_only_transformer\train
                startedAt: "2026-05-28T15:39:37.525283Z"
                writerId: 2vvaqteohyp5m5lwtun2a5loqid4xwrm
        m: []
        python_version: 3.11.15
        t:
            "1":
                - 1
                - 100
            "2":
                - 1
                - 100
            "3":
                - 13
                - 16
            "4": 3.11.15
            "5": 0.27.0
            "8":
                - 3
            "12": 0.27.0
            "13": windows-amd64
attention:
    value: standard
batch_size:
    value: 32
block_size:
    value: 64
context_window:
    value: 1024
conv_type:
    value: none
dropout:
    value: 0.2
embedding_size:
    value: 256
experiment_name:
    value: baseline
iterations:
    value: 10000
n_decoder_layers:
    value: 2
n_heads:
    value: 4
n_kv_heads:
    value: 2
positional_encoding:
    value: sinusoidal
run_name:
    value: null
use_conv:
    value: false
vocab_size:
    value: 50257
warmup_steps:
    value: 4000
window_size:
    value: 128
